id: it.indalo.lepiazze
name: Le Piazze
appname: lepiazze
description: Applicazione per centri commerciali
version: 1.0.0
short_version_string: 100
license: ISC
codice_cc: 7
author:
    name: Dolomiti Project
    email: sviluppo@dolomitiproject
    # al momento il campo url richiede che ogni simbolo `/` venga sostituito con un `\/` per supportare la sintassi di `sed`
    url: https://www.dolomitiproject.it
    email: sviluppo@dolomitiproject.it
